### ISSUE TITLE
"try catch {}" causing SyntaxError: Unexpected token { in node 8.11.3

### ISSUE THREAD

**Issue by gutimore** [sindresorhus/p-limit#54] opened 2021-04-30 17:29 UTC
Please guys, replace this expression in index.js:

		try { await result; } catch {}
		
for this one 

               try { await result; }  catch (e) {}
               
It's causing problems in older node versions

Thanks!

**Comment by sindresorhus** [comment] 2021-04-30 18:06
Duplicate of #33

**Closed by sindresorhus** 2021-04-30 18:06 UTC
