### ISSUE TITLE
Try/catch block failing in Jenkins build

### ISSUE THREAD

**Issue by andreidobrinski** [sindresorhus/p-limit#37] opened 2020-07-30 19:28 UTC
### Environment
React app, bundled with Webpack, deployed with Jenkins. Using p-limit through terser-webpack-plugin.

### Issue
Jenkins build fails with console output:
```
/path/to/repo/node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:30
		} catch {}
		        ^

SyntaxError: Unexpected token {
```

### Suggestion
I think it's expecting a condition to follow the `catch` keyword on index.js:30

Perhaps changing the following might work.
```
try {
  await result;
} catch {}
```
to
```
try {
  await result;
} catch (error) {}
```

Thanks! Please let me know if I can help further

**Comment by sindresorhus** [comment] 2020-07-31 09:50
Duplicate of #33

**Closed by sindresorhus** 2020-07-31 09:50 UTC
