### ISSUE TITLE
catch syntax error

### ISSUE THREAD

**Issue by FujianLuan** [sindresorhus/p-limit#36] opened 2020-07-28 03:36 UTC
when use the copy-webpack-plugin,the console show the error of catch syntax error , it's like forget the '(e)'
![image](https://user-images.githubusercontent.com/20737244/88616357-8f082880-d0c6-11ea-8b74-3dc35f482da7.png)

**Comment by sindresorhus** [comment] 2020-07-28 11:20
Duplicate of #33

**Closed by sindresorhus** 2020-07-28 11:20 UTC
