### ISSUE TITLE
this code is wrong

### ISSUE THREAD

**Issue by linger0239** [sindresorhus/p-limit#44] opened 2020-09-07 07:56 UTC
The try catch code on lines 28 to 31 is wrong，it should be 
`try {await result;} catch(e) {}`
Now, when i build my project, this wrong broken the process

**Comment by linger0239** [comment] 2020-09-07 07:56
this wrong in index.js

**Comment by sindresorhus** [comment] 2020-09-07 09:49
Duplicate of #33

**Closed by sindresorhus** 2020-09-07 09:49 UTC
